### ISSUE TITLE
Automatic dependency generation error (*.so.* -> package name)

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#25]
One of the packages I'm building seems to come up with a baffling set of automatic dependencies. The generated `Depends` line states the following:
```
Depends: libcurl3,libc6,libidn11,librtmp1,0,libgssapi-krb5-2,4-2,zlib1g,libgnutls-deb0-28,libhogweed4,libnettle6,libgmp10,libkrb5-3,libk5crypto3,libcomerr2,libkrb5support0,libsasl2-2,libgssapi3-heimdal,libp11-kit0,libtasn1-6,libkeyutils1,libheimntlm0-heimdal,libkrb5-26-heimdal,libasn1-8-heimdal,libhcrypto4-heimdal,libroken18-heimdal,libffi6,libwind0-heimdal,libheimbase1-heimdal,libhx509-5-heimdal,libsqlite3-0
```

Note that in that `Depends` list, there are two unresolvable dependencies: `0` and `4-2`. I have no idea where they came from!

This was generated from the following `BuildRequires` set:

```
BuildRequires:  libtool >= 2.2, make, gcc
BuildRequires:  pkg-config, libcurl4-openssl-dev
```

The binary had the following `ldd` output:
```
ngompa@u1510-dev-f23kvm:~$ ldd bin-out 
	linux-vdso.so.1 =>  (0x00007ffcbe368000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f4e29d41000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4e29b23000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4e29758000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f4e29525000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f4e29308000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f4e2909e000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f4e28c5c000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f4e28a12000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f4e28802000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f4e285b0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4e28396000)
	/lib64/ld-linux-x86-64.so.2 (0x00005627dd647000)
	libgnutls-deb0.so.28 => /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28 (0x00007f4e28079000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f4e27e46000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f4e27c10000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f4e2798f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4e2778b000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f4e274b9000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f4e27289000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f4e27085000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f4e26e7a000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4e26c5d000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f4e26a42000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f4e26802000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f4e2659c000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f4e26389000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f4e26184000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f4e25f7b000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f4e25cf1000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f4e25a4d000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f4e2581a000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f4e25605000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f4e253fc000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f4e251d3000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f4e24fc4000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f4e24d78000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f4e24aab000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f4e24873000)
```

I've been scratching my head (sometimes quite literally) over this problem, and I've got no clue how this is happening.

**Comment by ascherer** [comment]
The dot `.` in package names `libssl1.0.0` and `libldap-2.4-2` weren't scanned correctly, so the (parts of) the "version numbers" were extracted separately.

**Comment by ascherer** [comment]
My testscript for `ldd bin-out` above runs _very_ much faster
```
real    0m0.264s
user    0m0.172s
sys     0m0.052s
```
than invoking `dpkg-query` for each library file separately
```
real    0m8.230s
user    0m5.524s
sys     0m1.976s
```

**Comment by Conan-Kudo** [comment]
I encountered another case where this broke (after applying the patch for peculiar package names with dots).

Here's the `Depends` list:
```
Depends: libc6,libcurl3-gnutls,libsqlite3-0,libuuid1,libblkid1,libgcrypt11,libgnutls26,libmicrohttpd10,6,libgcc1,libidn11,librtmp0,libgssapi-krb5-2,libldap-2.4-2,zlib1g,libgpg-error0,libtasn1-6,libp11-kit0,libkrb5-3,libk5crypto3,libcomerr2,libkrb5support0,libsasl2-2,libgssapi3-heimdal,libffi6,libkeyutils1,libheimntlm0-heimdal,libkrb5-26-heimdal,libasn1-8-heimdal,libhcrypto4-heimdal,libroken18-heimdal,libwind0-heimdal,libheimbase1-heimdal,libhx509-5-heimdal
```
Here's the `ldd` output of the binary:
```
ngompa@ubuntu:~/Downloads$ ldd bin2-out 
	linux-vdso.so.1 =>  (0x00007ffe42bf1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f63d80fe000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f63d7e9c000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f63d7be3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f63d79c5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f63d77c0000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f63d759a000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f63d731a000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f63d705c000)
	libmicrohttpd.so.10 => /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10 (0x00007f63d6e45000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f63d6b41000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f63d683b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f63d6625000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f63d6260000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f63d602d000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f63d5e13000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f63d5bcd000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f63d59be000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f63d576d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f63d5554000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f63d5350000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f63d8306000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f63d514b000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f63d4f37000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f63d4cf5000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f63d4a2a000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f63d47fb000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f63d45f7000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f63d43ec000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f63d41d1000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f63d3fb6000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f63d3d78000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f63d3b70000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f63d396c000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f63d3763000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f63d34db000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f63d323a000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f63d3007000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f63d2df2000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f63d2bc9000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f63d29bb000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f63d2772000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f63d2539000)
```

This was on Ubuntu 14.04.

**Comment by ascherer** [comment]
Please try `60bd881` instead. In the 'peculiar' change I only added dot `.`, while in 'speed up' i changed to "everything but whitespace". I'll test in 3..2..1.

**Comment by Conan-Kudo** [comment]
@ascherer Nope. That messes things up even more. Now `amd64` AND `6` are dependencies somehow.

**Comment by ascherer** [comment]
Commit 60bd881 works for me (resp. the equivalent test script). You can try yourself by using the `getreqs.pl` script in commit a7a9736. The list of `ldd bin2-out` is transformed into
```
$VAR1 = 'libc6';
$VAR2 = 'libcurl3-gnutls';
$VAR3 = 'libsqlite3-0';
$VAR4 = 'libc6';
$VAR5 = 'libuuid1';
$VAR6 = 'libblkid1';
$VAR7 = 'libgcrypt11';
$VAR8 = 'libgnutls26';
$VAR9 = 'libstdc++6';
$VAR10 = 'libc6';
$VAR11 = 'libgcc1';
$VAR12 = 'libc6';
$VAR13 = 'libidn11';
$VAR14 = 'librtmp0';
$VAR15 = 'libgssapi-krb5-2';
$VAR16 = 'libldap-2.4-2';
$VAR17 = 'libldap-2.4-2';
$VAR18 = 'zlib1g';
$VAR19 = 'libc6';
$VAR20 = 'libgpg-error0';
$VAR21 = 'libp11-kit0';
$VAR22 = 'libkrb5-3';
$VAR23 = 'libk5crypto3';
$VAR24 = 'libcomerr2';
$VAR25 = 'libkrb5support0';
$VAR26 = 'libc6';
$VAR27 = 'libsasl2-2';
$VAR28 = 'libgssapi3-heimdal';
$VAR29 = 'libffi6';
$VAR30 = 'libkeyutils1';
$VAR31 = 'libheimntlm0-heimdal';
$VAR32 = 'libkrb5-26-heimdal';
$VAR33 = 'libasn1-8-heimdal';
$VAR34 = 'libhcrypto4-heimdal';
$VAR35 = 'libroken18-heimdal';
$VAR36 = 'libwind0-heimdal';
$VAR37 = 'libheimbase1-heimdal';
$VAR38 = 'libhx509-5-heimdal';
$VAR39 = 'libc6';
```
so `+` is correctly processed, at least no single `6` is spit out (I have no idea where the `amd64` comes from). Note that my vintage Samsung R50 with Kubuntu 12.04 requires that I mogrify `x86_64` into `i386`. And on this system, `dpkg-query -S` doesn't find library files
```
/usr/lib/i386-linux-gnu/libmicrohttpd.so.10
/usr/lib/i386-linux-gnu/libtasn1.so.6
```
These may come from `libmicrohttpd5` and `libtasn1-3` (which has `/usr/lib/i386-linux-gnu/libtasn1.so.3` installed).

**Comment by Conan-Kudo** [comment]
@ascherer I've been testing on Debian wheezy, Debian jessie, Ubuntu precise, and Ubuntu trusty and have been able to reliably reproduce this issue with an internal package on amd64 (the package does not build on i386, as it's 64-bit only software).

**Comment by ascherer** [comment]
What's the output of `dpkg-query -S` for that package? Could it be that there is some extra `:` lurking?

**Comment by Conan-Kudo** [comment]
@ascherer How would I get you the output for that? debbuild seems to hide that from me...

**Comment by ascherer** [comment]
Please use the perl script `getreqs.pl` from commit a7a9736.

**Comment by ascherer** [comment]
I think I fixed it. See the last commit for the cool trick. :wink:

**Comment by Conan-Kudo** [comment]
@ascherer It is still broken on all four targets I've been testing against (Ubuntu precise, Ubuntu trusty, Debian wheezy, and Debian jessie).

**Comment by ascherer** [comment]
Brilliant idea: Merge the two versions by `map`ping the output of `qx()` with the _old_ regexp. Will do that tomorrow. Bye for now.

**Comment by ascherer** [comment]
```
return map { m/^(\S+?):/ } qx($specglobals{__dpkg_query} -S$reqliblist);
```

**Comment by Conan-Kudo** [comment]
As of a0db009, this doesn't appear to be an issue anymore.

**Comment by ascherer** [comment]
Thanks for spotting this and insisting on a solid solution. :+1:
